language: generic
sudo: false

notifications:
  webhooks:
    urls:
      - https://discordapp.com/api/webhooks/519412068567482368/5d8kpkHTDA_Yqz2deI4as4jCGsv1vrhgHDJnbOtCrf7W8q3Y-7n_JDKVDxC-95hO-4bH
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

env:
    global:
    - BYOND_MAJOR="512"
    - BYOND_MINOR="1454"
    - DM_BUILDFILE="taucetistation.dme"

cache:
  directories:
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}

addons:
  apt:
    packages:
      - libc6-i386
      - libgcc1:i386
      - libstdc++6:i386

before_script:
  - chmod +x ./install-byond.sh 
  - ./install-byond.sh

script:
  - source $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}/byond/bin/byondsetup
  - bash dm.sh ${DM_BUILDFILE}
