#define LAVA_TURF_TEMP 343.15
#define LAVA_TURF_O2 (MOLES_CELLSTANDARD * 0.18)
#define LAVA_TURF_CO2 (MOLES_CELLSTANDARD * 0.01)
#define LAVA_TURF_N (MOLES_CELLSTANDARD * 0.81)

#define PLANET_SIZE_X 150
#define PLANET_SIZE_Y 150